linters:
  disable-all: true

  enable:
#    - gosimple
#    - govet
#    - ineffassign
#    - staticcheck
#    - bodyclose
#    - dupl
#    - exportloopref
#    - funlen
#    - gocognit
#    - goconst
#    - gocritic
#    - gocyclo
#    - stylecheck
#    - whitespace
#    - goprintffuncname
#    - gosec
#    - interfacer
#    - maligned
#    - prealloc
#    - revive
#    - errorlint
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - exportloopref
    - govet
    - gosimple
    - gofmt
    - gofumpt
    - goconst
    - goimports
    - gomnd
    - gocyclo
    - ineffassign
    - lll
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unused
    - whitespace
    - wastedassign
    - unconvert
    - misspell