codecov:
  require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: yes

ignore:
  - '**/*.pb.go'

fixes:
  - github.com/go-fries/fries/v4::./
  - github.com/go-fries/fries/batcher/v4::batcher/
  - github.com/go-fries/fries/cache/v4::cache/
  - github.com/go-fries/fries/cache/redis/v4::cache/redis/
  - github.com/go-fries/fries/chi/v4::chi/
  - github.com/go-fries/fries/cloudevents/protocol/amqp091/v4::cloudevents/protocol/amqp091/
  - github.com/go-fries/fries/cloudevents/eventdispatcher/v4::cloudevents/eventdispatcher/
  - github.com/go-fries/fries/codec/v4::codec/
  - github.com/go-fries/fries/codec/json/v4::codec/json/
  - github.com/go-fries/fries/codec/msgpack/v4::codec/msgpack/
  - github.com/go-fries/fries/codec/sonic/v4::codec/sonic/
  - github.com/go-fries/fries/codec/proto/v4::codec/proto/
  - github.com/go-fries/fries/codec/xml/v4::codec/xml/
  - github.com/go-fries/fries/codec/yaml/v4::codec/yaml/
  - github.com/go-fries/fries/config/v4::config/
  - github.com/go-fries/fries/constraints/v4::constraints/
  - github.com/go-fries/fries/capability/v4::capability/
  - github.com/go-fries/fries/parallel/v4::parallel/
  - github.com/go-fries/fries/crontab/v4::crontab/
  - github.com/go-fries/fries/encrypter/v4::encrypter/
  - github.com/go-fries/fries/ent/v4::ent/
  - github.com/go-fries/fries/ent/multidriver/v4::ent/multidriver/
  - github.com/go-fries/fries/env/v4::env/
  - github.com/go-fries/fries/errors/v4::errors/
  - github.com/go-fries/fries/event/v4::event/
  - github.com/go-fries/fries/event/middleware/recovery/v4::event/middleware/recovery/
  - github.com/go-fries/fries/filesystem/v4::filesystem/
  - github.com/go-fries/fries/filesystem/local/v4::filesystem/local/
  - github.com/go-fries/fries/filesystem/oss/v4::filesystem/oss/
  - github.com/go-fries/fries/filesystem/s3/v4::filesystem/s3/
  - github.com/go-fries/fries/lifecycle/v4::lifecycle/
  - github.com/go-fries/fries/gin/v4::gin/
  - github.com/go-fries/fries/gorm/logger/multi/v4::gorm/logger/multi/
  - github.com/go-fries/fries/gorm/logger/otel/v4::gorm/logger/otel/
  - github.com/go-fries/fries/gorm/scope/v4::gorm/scope/
  - github.com/go-fries/fries/hashing/v4::hashing/
  - github.com/go-fries/fries/hashing/md5/v4::hashing/md5/
  - github.com/go-fries/fries/health/v4::health/
  - github.com/go-fries/fries/idempotency/v4::idempotency/
  - github.com/go-fries/fries/idempotency/memory/v4::idempotency/memory/
  - github.com/go-fries/fries/idempotency/redis/v4::idempotency/redis/
  - github.com/go-fries/fries/http/response/v4::http/response/
  - github.com/go-fries/fries/http/server/v4::http/server/
  - github.com/go-fries/fries/hyperf/jet/v4::hyperf/jet/
  - github.com/go-fries/fries/hyperf/jet/middleware/logger/v4::hyperf/jet/middleware/logger/
  - github.com/go-fries/fries/hyperf/jet/middleware/recovery/v4::hyperf/jet/middleware/recovery/
  - github.com/go-fries/fries/hyperf/jet/middleware/retry/v4::hyperf/jet/middleware/retry/
  - github.com/go-fries/fries/hyperf/jet/middleware/timeout/v4::hyperf/jet/middleware/timeout/
  - github.com/go-fries/fries/hyperf/jet/middleware/otel/v4::hyperf/jet/middleware/otel/
  - github.com/go-fries/fries/log/slog/v4::log/slog/
  - github.com/go-fries/fries/log/slog/multi/v4::log/slog/multi/
  - github.com/go-fries/fries/log/slog/syslog/v4::log/slog/syslog/
  - github.com/go-fries/fries/kratos/middleware/cors/v4::kratos/middleware/cors/
  - github.com/go-fries/fries/kratos/middleware/protovalidate/v4::kratos/middleware/protovalidate/
  - github.com/go-fries/fries/kratos/middleware/otel/v4::kratos/middleware/otel/
  - github.com/go-fries/fries/locker/v4::locker/
  - github.com/go-fries/fries/locker/redis/v4::locker/redis/
  - github.com/go-fries/fries/queue/v4::queue/
  - github.com/go-fries/fries/queue/adapter/memory/v4::queue/adapter/memory/
  - github.com/go-fries/fries/queue/adapter/rabbitmq/v4::queue/adapter/rabbitmq/
  - github.com/go-fries/fries/queue/adapter/redis/v4::queue/adapter/redis/
  - github.com/go-fries/fries/queue/kratos/server/v4::queue/kratos/server/
  - github.com/go-fries/fries/queue/middleware/recovery/v4::queue/middleware/recovery/
  - github.com/go-fries/fries/ratelimit/v4::ratelimit/
  - github.com/go-fries/fries/ratelimit/memory/v4::ratelimit/memory/
  - github.com/go-fries/fries/ratelimit/redis/v4::ratelimit/redis/
  - github.com/go-fries/fries/mysql/canal/v4::mysql/canal/
  - github.com/go-fries/fries/mysql/canal/positioner/redis/v4::mysql/canal/positioner/redis/
  - github.com/go-fries/fries/mysql/canal/server/v4::mysql/canal/server/
  - github.com/go-fries/fries/otel/otlp/v4::otel/otlp/
  - github.com/go-fries/fries/poll/v4::poll/
  - github.com/go-fries/fries/ptr/v4::ptr/
  - github.com/go-fries/fries/recovery/v4::recovery/
  - github.com/go-fries/fries/retry/v4::retry/
  - github.com/go-fries/fries/signal/v4::signal/
  - github.com/go-fries/fries/support/v4::support/
  - github.com/go-fries/fries/timezone/v4::timezone/
  - github.com/go-fries/fries/udp/v4::udp/
  - github.com/go-fries/fries/webhook/v4::webhook/
  - github.com/go-fries/fries/webhook/sender/v4::webhook/sender/
  - github.com/go-fries/fries/x/container/v4::x/container/
  - github.com/go-fries/fries/x/pagination/v4::x/pagination/
  - github.com/go-fries/fries/x/prints/v4::x/prints/
  - github.com/go-fries/fries/eino/components/embedding/cached/v4::eino/components/embedding/cached/
  - github.com/go-fries/fries/eino/components/embedding/cached/example/v4::eino/components/embedding/cached/example/
  - github.com/go-fries/fries/eino/components/embedding/cached/cacher/redis/v4::eino/components/embedding/cached/cacher/redis/
  - github.com/go-fries/fries/eino/components/embedding/cached/cacher/gorm/v4::eino/components/embedding/cached/cacher/gorm/
  - github.com/go-fries/fries/slices/v4::slices/
  - github.com/go-fries/fries/strings/v4::strings/
  - github.com/go-fries/fries/jsonrpc/v4::jsonrpc/
  - github.com/go-fries/fries/queue/examples/tasker/v4::queue/examples/tasker/
