name: Go Lint

on:
  push:
    branches:
      - 1.x
      - 2.x
  pull_request:
    branches:
      - 1.x
      - 2.x

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4